# Bot login settings
mw_server_url: 'http://wiki.localhost'
mw_server_path: '/'
mw_username: 'mobobot'
mw_password: 'password'
mw_server_port: false

# Custom Settings
uploadWikiPages: true
deleteWikiPages: false
